// export const SERVER_URL = "http://localhost:5001";
export const SERVER_URL = "https://leap-backend.vercel.app";
// client X wallet address
export const WALLET_ADDRESS = "G28ABSiZBcdQV57fmPYTUjwZuWMSJKUwoiUSfxPs6SRE"
export const DEVELOPMENT_EDITOR = "eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NzAwNzY3OTksImp0aSI6IjFkMDhhYTQ5LTMyOTMtNDU5OC05MGI2LTExM2QwNjc4ZDYwNSIsImxpY2Vuc2VkSG9zdHMiOlsiMTI3LjAuMC4xIiwibG9jYWxob3N0IiwiMTkyLjE2OC4qLioiLCIxMC4qLiouKiIsIjE3Mi4qLiouKiIsIioudGVzdCIsIioubG9jYWxob3N0IiwiKi5sb2NhbCJdLCJ1c2FnZUVuZHBvaW50IjoiaHR0cHM6Ly9wcm94eS1ldmVudC5ja2VkaXRvci5jb20iLCJkaXN0cmlidXRpb25DaGFubmVsIjpbImNsb3VkIiwiZHJ1cGFsIl0sImxpY2Vuc2VUeXBlIjoiZGV2ZWxvcG1lbnQiLCJmZWF0dXJlcyI6WyJEUlVQIl0sInZjIjoiODliYzg3MTgifQ.g5V26QJztT7u0y4In-SjtHMNVdjk5HrzixQMoUL6x9EqcUh66m99V9KwsnGfD3DmkL_dQ4SkThX4l85G9GVjdw";
export const PRODUCTION_EDITOR = "eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NzAwNzY3OTksImp0aSI6IjE2YWIyMjViLWRjYzAtNDMwYS1hMmQyLTk1ZWVlNTVlMzhjZSIsInVzYWdlRW5kcG9pbnQiOiJodHRwczovL3Byb3h5LWV2ZW50LmNrZWRpdG9yLmNvbSIsImRpc3RyaWJ1dGlvbkNoYW5uZWwiOlsiY2xvdWQiLCJkcnVwYWwiXSwiZmVhdHVyZXMiOlsiRFJVUCJdLCJ2YyI6ImUxNmFkNmFlIn0.wkFoD1CMLZ4ntU5-xf6A5Z4sk6FmsutI7ee47fHAz2xc-106ax4CJ-eXl0IUAQ7wzlRgeBXFizUDZe4xdIK5zA";
// clients token dynamic.xyz
export const DYNAMIC_XYZ_TOKEN = "dyn_7MQWkmtdSsnj0SDeDckM9FBjK65nekLZGYYsKmftdMbHC2XUHQ3iwGO6"

// tool solana rpc url for live and dev
export const SOL_RPC_URL = "https://api.devnet.solana.com";
//export const SOL_RPC_URL = "https://api.mainnet-beta.solana.com";



